#!/bin/sh
#
# Author: Rob Hamilton
# Fri Jul 20 02:13:17 BST 2018
#
# $Date: 2018-07-31 07:03:24 +0100 (Tue, 31 Jul 2018) $
# $URL: svn://kit/projects/thinkpad/bin/snap $
# $Rev: 194 $

PATH=/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin
progname=`basename $0`

usage() {

  cat <<EOF
    usage:
    $progname [-n (dryrun)] [-b (work on zbackup/backups)] cmd
    eg.
    $progname list [snapshot matchexpr]  (show snapshots)
    $progname cat [snapshot matchexpr] 
    $progname ls [lsargs] snapname[:relpath] (ls files in snapshots(
    $progname [diff|get] [args] snap:relpath (diff or cp from(
    $progname create|destroy snapshot
    NB path is relative. -b selects zbackup/backups, -n is dry run.
    ls/diff/get (= one way cp) can take any args
EOF
    exit 1
}

dryrun=false
zpool=zroot
mprefix=""

while getopts "hnb" opt ; do
    case $opt in
	n)
	    dryrun=true
	    echo 'dryrun only. nothing changed on disk'
	    ;;
	b)
	    #zpool=$OPTARG
	    zpool="zackup"
	    mprefix="/zbackup/backups"
	    ;;
	h)
	    usage
	    ;;
    esac
done

shift $((OPTIND-1))

if [ -z "$zpool" ] ; then
    echo no pool specified
    exit 1
fi

now=`date +%H`

case $1 in 
    list)
	if [ ! -z "$2" ] ; then 
	    zfs list -t snapshot|grep "$2"
	else  
	    zfs list -t snapshot
	fi
	;;

    create)
	what=$2
	if [ -z "$2" ] ; then
	    what=$now
	fi
	if $dryrun ; then
	    echo zfs snapshot -r ${zpool}@$what
	else
	    zfs snapshot -r ${zpool}@$what
	fi
	;;

    destroy)
	what=$2
	if [ -z "$2" ] ; then
	    echo no fs specified. try -h
	    exit 1
	fi
	if $dryrun ; then
	    echo zfs destroy -r ${zpool}@$what
	else
	    zfs destroy -r ${zpool}@$what
	fi
	;;
    ls|get|diff|cat) # working in home dir only for now xxx
	prog=$1
	arg=""
	case $2 in
	    -*)
		arg="$2"
		shift
		;;
	esac
	if [ "$1" = "ls" -a -z "$2" ] ; then # special for ls just show snaps
	    what=${mprefix}/usr/home/.zfs/snapshot/
	    echo $what
	    ls $arg $what
	    exit 0
	fi
	snapname=$(echo $2|awk -F:  '{print $1}')
	if [ -z "$snapname" ] ; then
	    echo no snapshot given try -h
	    exit 1
	fi
	what=$(echo $2|awk -F:  '{print $2}')
	where=`pwd | ruby -e 'print STDIN.read.split("/")[2..100].join("/")'`
	tail=""
	case $prog in
    cat)
      tail=""
      cmd="cat"
      ;;
	    get)
		tail="."
		cmd="cp"
		;;
	    ls)
		tail=""
		cmd="ls"
		;;
	    diff)
		tail="$what"
		cmd="diff"
		;;
	    *)
		unexpected command $prog
		exit 1
	esac
	if $dryrun ; then 
	    echo would do:
	    echo $cmd $arg ${mprefix}/usr/home/.zfs/snapshot/$snapname/$where/$what $tail
	else
	    $cmd $arg ${mprefix}/usr/home/.zfs/snapshot/$snapname/$where/$what $tail
	fi
	;;
    *)
	usage
	;;
esac


